cost = list(map(int, input('цены предметов (разделённых пробелами) ').split()))
cost_up=cost.copy()
cost_up.sort(reverse=False)
print(f'Сортировка по возрастанию: {cost_up}')
cost_down=cost.copy()
cost_down.sort(reverse=True)
print(f'Сортировка по убыванию: {cost_down}')
print(f'Оригинальный порядок: {cost}')
cost.reverse()
print(f'Обратный порядок: {cost}')
